21 deadlock integration
Nuozrok/lpap pull request #24
Opened 2024-12-19 04:16 UTC by whig123

3 commands added
/deadlockpatchnotes
/deadlockstats
/deadlocklinkaccount
/hayes

2024-12-19 04:47 UTC, Nuozrok requested changes

2024-12-19 04:47 UTC, Nuozrok commented on commands/hayes.js
what on earth

2024-12-19 04:47 UTC, Nuozrok commented on data/accountscache.json
Is this safe to keep on the GitHub? I guess these are all public numbers/ids?

2024-12-19 04:47 UTC, Nuozrok commented on data/exampledeadlockdata.json
Example file. Redundant?

2024-12-19 04:47 UTC, Nuozrok commented on data/exampledeadlockpatchnotes.json
Example file. Redundant?

2024-12-19 04:47 UTC, Nuozrok commented on data/hayesdata.txt
Weird formatting in this. Just look at the first line. 'IPAcenrVrfrdaudioenusRutherfordoga'

2024-12-19 04:47 UTC, Nuozrok commented on package.json
Will this break distube as described in issue #22?

2024-12-19 04:47 UTC, Nuozrok commented on data/accountscache.json
GitGuardian check deems it safe.

2024-12-19 23:22 UTC, whig123 commented on commands/hayes.js
looks good to me

2024-12-19 23:22 UTC, whig123 commented on data/accountscache.json
this is all public info. the steamID is what you see on their profile. the rest of it is all details you can see on someone else's profile

2024-12-19 23:24 UTC, whig123 commented on data/exampledeadlockdata.json
yeah we don't need it, deleted

2024-12-19 23:25 UTC, whig123 commented on data/hayesdata.txt
the people get what they want, they asked for hayes, I deliver hayes

2024-12-19 23:26 UTC, whig123 commented on package.json
what version of node is production bot running on? if it is running on 18.20.5 LTS or earlier we should be fine, if it is running later then yes but the bot would already be broken

2024-12-19 23:28 UTC, whig123 reviewed
give the deadlock players what they deserve

2024-12-19 23:43 UTC, Nuozrok commented on package.json
<img width="217" alt="Screenshot 2024-12-19 at 6 41 41 PM" src="https://github.com/user-attachments/assets/262ebeee-afd5-4c5d-a2cc-ce952e907057" />

2024-12-19 23:43 UTC, Nuozrok commented on package.json
should be good then

2024-12-19 23:46 UTC, whig123 commented on package.json
let me test on my machine though while we still have 2 copies

2024-12-19 23:46 UTC, Nuozrok commented on data/experimental/deadlocksingularmatchexample.json
example? redundant?

2024-12-19 23:46 UTC, whig123 commented on package.json
to test the /play command

2024-12-19 23:46 UTC, Nuozrok commented on data/experimental/example_protobuf.bz2
example? redundant?

2024-12-19 23:46 UTC, Nuozrok commented on data/experimental/example_protobuf/example_protobuf
example? redundant?

2024-12-19 23:47 UTC, Nuozrok commented on data/exampledeadlockdata.json
delete empty file

2024-12-19 23:47 UTC, Nuozrok requested changes
address comments

2024-12-19 23:59 UTC, whig123 commented on package.json
did you have to set up ffmpeg originally to get distube to work? it is asking me to install that on my pc when I'm testing that distube still works

2024-12-20 00:12 UTC, Nuozrok commented on package.json
yes

2024-12-21 02:06 UTC, whig123 reviewed
give the people what they want2

2024-12-21 05:30 UTC, Nuozrok commented
@whig123  please document commands on the [wiki](https://github.com/Nuozrok/lpap/wiki/Commands)

2024-12-22 21:28 UTC, whig123 commented
give the people what they want3

2024-12-22 21:35 UTC, Nuozrok approved these changes

2024-12-22 21:35 UTC, merged